<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Cielo' => array($vendorDir . '/developercielo/api-3.0-php/src'),
    'Barryvdh' => array($vendorDir . '/barryvdh/reflection-docblock/src'),
);
